# @package hydra
run:
    dir: /checkpoint/${oc.env:USER}/moco_clip/${logging.name}/outputs/
sweep:
    dir: /checkpoint/${oc.env:USER}/moco_clip/${logging.name}/outputs/
    subdir: ID${hydra.job.id} 
