arch: 'resnet50'
sentence_model: 'distilbert-base-uncased'
moco_k: 65536  # queue/buffer size. MoCo default is 65536
moco_t: 0.07   # temperature (default based on CLIP; not learnable)
moco_m: 0.999  # not used in moco-clip
moco_dim: 128  # not used unless MLP projection is used
mlp: False
pretrained: False
load_path: ''
sync_bn: False
